spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    master:
      jdbc-url: jdbc:sqlserver://172.16.0.155:1433;database=zncssd
      username: sa
      password: Test@123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    slave:
      jdbc-url: jdbc:mysql://139.9.71.89:3306/de_dicom?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: Fengmu@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      enabled: true
  jpa:
    show-sql: true

