# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.fzong: debug
    org.springframework: warn

# Spring配置
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
    mode: HTML
  profiles: 
    active: hikari
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

job:
  #60s 同步任务执行间隔 不超过3分钟 默认60s
  fixedRate: 60000
